name: Cleanup environments

on:
  pull_request:
    types:
      - closed
      - merged
  workflow_dispatch:

jobs:
  cleanup:
    uses: blockscout/blockscout-ci-cd/.github/workflows/cleanup.yaml@master
    with:
      appNamespace: review-front-$GITHUB_HEAD_REF_SLUG
      dockerImage: prerelease-$GITHUB_SHA_SHORT
    secrets: inherit
