name: Cleanup environments

on:
  pull_request:
    types:
      - closed
      - merged
  workflow_dispatch:

jobs:
  cleanup:
    uses: blockscout/blockscout-ci-cd/.github/workflows/cleanup.yaml@nz-cleanup-fix
    with:
      appName: review-l2-$GITHUB_REF_NAME_SLUG
      globalEnv: review
      helmfileDir: deploy
      kubeConfigSecret: ci/data/dev/kubeconfig/k8s-dev
      vaultRole: ci-dev
      dockerImage: prerelease-$GITHUB_REF_NAME_SLUG
    secrets: inherit
  cleanup_l2:
    uses: blockscout/blockscout-ci-cd/.github/workflows/cleanup.yaml@nz-cleanup-fix
    with:
      appName: review-$GITHUB_REF_NAME_SLUG
      globalEnv: review
      helmfileDir: deploy
      kubeConfigSecret: ci/data/dev/kubeconfig/k8s-dev
      vaultRole: ci-dev
      dockerImage: prerelease-$GITHUB_REF_NAME_SLUG
    secrets: inherit
