name: Playwright
on:
  workflow_run:
    workflows: ["Linters"]
    types:
      - completed

jobs:
  test:
    name: Run visual components test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.27.0-focal

    steps:
      - run: apt-get update && apt-get install git-lfs
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run your tests
        run: HOME=/root yarn test-ct
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report