name: Pre-release

on:
    workflow_dispatch:
    push:
        tags:
            - 'v**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }} # Release-refs/tags/v1.0.0
    cancel-in-progress: true

jobs:
    checks:
        name: Run code checks
        uses: "./.github/workflows/checks.yml"
        secrets: inherit

    e2e_tests:
        name: Run e2e tests
        needs: checks
        uses: "./.github/workflows/e2e-tests.yml"
        secrets: inherit

