name: Release

on:
    workflow_dispatch:
    release:
        types: [ released ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }} # Release-refs/tags/v1.0.0
    cancel-in-progress: true

jobs:
    label_released_issues:
        name: Label released issues
        uses: './.github/workflows/label-released-issues.yml'
        secrets: inherit
    update_project_cards:
        name: Update project tasks statuses
        needs: label_released_issues
        uses: './.github/workflows/update-project-cards.yml'
        with:
            project_name: ${{ vars.PROJECT_NAME }}
            field_name: Status
            field_value: Released
            issues: ${{ needs.label_released_issues.outputs.issues }}
        secrets: inherit

