name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  sync:
    name: Sync with Upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release from upstream
        id: get_latest_release
        run: |
          UPSTREAM_URL="https://github.com/blockscout/frontend"
          UPSTREAM_BRANCH="main"
          LATEST_RELEASE=$(git ls-remote --tags "$UPSTREAM_URL" | awk '{print $2}' | cut -d "/" -f 3 | sort -V | tail -n 1)
          echo "::set-output name=latest_release::$LATEST_RELEASE"

      - name: Check if there's a new release
        id: check_release
        run: |
          LOCAL_BRANCH="<your_local_branch_name>"
          UPSTREAM_BRANCH="<upstream_branch_name>"
          if git merge-base --is-ancestor "$LOCAL_BRANCH" "$UPSTREAM_BRANCH"; then
            echo "::set-output name=release_exists::false"
          else
            echo "::set-output name=release_exists::true"
          fi

      - name: Sync with upstream if a new release exists
        if: steps.check_release.outputs.release_exists == 'true'
        run: |
          UPSTREAM_BRANCH="<upstream_branch_name>"
          git fetch upstream "$UPSTREAM_BRANCH"
          git rebase "upstream/$UPSTREAM_BRANCH"
          git push origin "$UPSTREAM_BRANCH"
